version: "3"
services:
  app:
    container_name: fixmycity-s
    restart: always
    build: .
    ports:
      - 1000:1000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - data:/data/db
volumes: 
  data:
